log_level                :info
log_location             STDOUT
node_name                'monika'
client_key               '/home/monika/tutorial/.chef/monika.pem'
validation_client_name   'chef-validator'
validation_key           '/home/monika/tutorial/.chef/chef-validator.pem'
chef_server_url          'https://10.21.1.9:443'
syntax_check_cache_path  '/home/monika/tutorial/.chef/syntax_check_cache'
cookbook_path            '/home/monika/tutorial/cookbooks'
